python show_finish.py 4 400 random
python show_finish.py 4 400 min_max_flows
python show_finish.py 4 25 random
python show_finish.py 4 25 min_max_flows
python show_finish.py 4 10 random
python show_finish.py 4 10 min_max_flows
python show_finish.py 2 10 random
python show_finish.py 2 10 min_max_flows
python show_finish.py 1 10 random
python show_finish.py 1 10 min_max_flows